name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      tag:
        type: string
        required: true
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to the Registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.registry_username}}
          password: ${{secrets.registry_password}}
