name: Cloud Corfu Cleint Build

on: workflow_dispatch

jobs:
  corfu-client-docker:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
     - uses: ./.github/workflows/docker/docker.yml
      with:
        image_name: "my-awesome-app"
        tag: "yay"
      #secrets:
       # registry_username: ${{ secrets.REGISTRY_USERNAME }}
        #registry_password: ${{ secrets.REGISTRY_PASSWORD }}
