name: Cloud Corfu Cleint Build

on: workflow_dispatch

jobs:
  corfu-client-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/docker/docker.yml@v1
        with:
          image_name: my-awesome-app
          tag: $GITHUB_RUN_NUMBER
        #secrets:
         # registry_username: ${{ secrets.REGISTRY_USERNAME }}
          #registry_password: ${{ secrets.REGISTRY_PASSWORD }}
