name: Cloud Corfu Cleint Build

on: workflow_dispatch

jobs:
  test_job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
  
      - name: test test test
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: |
          make test_test
